# Do NOT update manually; changes here will be overwritten by Copier
_src_path: ./
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
customer_repo: true
generate_requirements_txt: true
github_add_codeowners: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: IFE Gesellschaft für Forschung und Entwicklung
org_slug: ifegmbh
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: ass
repo_website: https://www.ife.de
use_pyproject_toml: true
use_ruff: true

